(cl:defpackage path_exam-msg
  (:use )
  (:export
   "<RECORDODOMACTION>"
   "RECORDODOMACTION"
   "<RECORDODOMACTIONFEEDBACK>"
   "RECORDODOMACTIONFEEDBACK"
   "<RECORDODOMACTIONGOAL>"
   "RECORDODOMACTIONGOAL"
   "<RECORDODOMACTIONRESULT>"
   "RECORDODOMACTIONRESULT"
   "<RECORDODOMFEEDBACK>"
   "RECORDODOMFEEDBACK"
   "<RECORDODOMGOAL>"
   "RECORDODOMGOAL"
   "<RECORDODOMRESULT>"
   "RECORDODOMRESULT"
  ))

