; Auto-generated. Do not edit!


(cl:in-package path_exam-msg)


;//! \htmlinclude RecordOdomFeedback.msg.html

(cl:defclass <RecordOdomFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass RecordOdomFeedback (<RecordOdomFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <RecordOdomFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'RecordOdomFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name path_exam-msg:<RecordOdomFeedback> is deprecated: use path_exam-msg:RecordOdomFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <RecordOdomFeedback>) ostream)
  "Serializes a message object of type '<RecordOdomFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <RecordOdomFeedback>) istream)
  "Deserializes a message object of type '<RecordOdomFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<RecordOdomFeedback>)))
  "Returns string type for a message object of type '<RecordOdomFeedback>"
  "path_exam/RecordOdomFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'RecordOdomFeedback)))
  "Returns string type for a message object of type 'RecordOdomFeedback"
  "path_exam/RecordOdomFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<RecordOdomFeedback>)))
  "Returns md5sum for a message object of type '<RecordOdomFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'RecordOdomFeedback)))
  "Returns md5sum for a message object of type 'RecordOdomFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<RecordOdomFeedback>)))
  "Returns full string definition for message of type '<RecordOdomFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'RecordOdomFeedback)))
  "Returns full string definition for message of type 'RecordOdomFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <RecordOdomFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <RecordOdomFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'RecordOdomFeedback
))
