; Auto-generated. Do not edit!


(cl:in-package path_exam-msg)


;//! \htmlinclude RecordOdomGoal.msg.html

(cl:defclass <RecordOdomGoal> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass RecordOdomGoal (<RecordOdomGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <RecordOdomGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'RecordOdomGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name path_exam-msg:<RecordOdomGoal> is deprecated: use path_exam-msg:RecordOdomGoal instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <RecordOdomGoal>) ostream)
  "Serializes a message object of type '<RecordOdomGoal>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <RecordOdomGoal>) istream)
  "Deserializes a message object of type '<RecordOdomGoal>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<RecordOdomGoal>)))
  "Returns string type for a message object of type '<RecordOdomGoal>"
  "path_exam/RecordOdomGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'RecordOdomGoal)))
  "Returns string type for a message object of type 'RecordOdomGoal"
  "path_exam/RecordOdomGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<RecordOdomGoal>)))
  "Returns md5sum for a message object of type '<RecordOdomGoal>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'RecordOdomGoal)))
  "Returns md5sum for a message object of type 'RecordOdomGoal"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<RecordOdomGoal>)))
  "Returns full string definition for message of type '<RecordOdomGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'RecordOdomGoal)))
  "Returns full string definition for message of type 'RecordOdomGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <RecordOdomGoal>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <RecordOdomGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'RecordOdomGoal
))
