// Generated by gencpp from file path_exam/RecordOdomResult.msg
// DO NOT EDIT!


#ifndef PATH_EXAM_MESSAGE_RECORDODOMRESULT_H
#define PATH_EXAM_MESSAGE_RECORDODOMRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace path_exam
{
template <class ContainerAllocator>
struct RecordOdomResult_
{
  typedef RecordOdomResult_<ContainerAllocator> Type;

  RecordOdomResult_()
    : result()  {
    }
  RecordOdomResult_(const ContainerAllocator& _alloc)
    : result(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::geometry_msgs::Pose_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Pose_<ContainerAllocator> >::other >  _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::path_exam::RecordOdomResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::path_exam::RecordOdomResult_<ContainerAllocator> const> ConstPtr;

}; // struct RecordOdomResult_

typedef ::path_exam::RecordOdomResult_<std::allocator<void> > RecordOdomResult;

typedef boost::shared_ptr< ::path_exam::RecordOdomResult > RecordOdomResultPtr;
typedef boost::shared_ptr< ::path_exam::RecordOdomResult const> RecordOdomResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::path_exam::RecordOdomResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::path_exam::RecordOdomResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace path_exam

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'path_exam': ['/home/user/catkin_ws/devel/share/path_exam/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::path_exam::RecordOdomResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::path_exam::RecordOdomResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::path_exam::RecordOdomResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::path_exam::RecordOdomResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::path_exam::RecordOdomResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::path_exam::RecordOdomResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::path_exam::RecordOdomResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "36fd4b93ec7a27bfb5a24dddce9d2550";
  }

  static const char* value(const ::path_exam::RecordOdomResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x36fd4b93ec7a27bfULL;
  static const uint64_t static_value2 = 0xb5a24dddce9d2550ULL;
};

template<class ContainerAllocator>
struct DataType< ::path_exam::RecordOdomResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "path_exam/RecordOdomResult";
  }

  static const char* value(const ::path_exam::RecordOdomResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::path_exam::RecordOdomResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#result\n\
geometry_msgs/Pose[] result\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::path_exam::RecordOdomResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::path_exam::RecordOdomResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RecordOdomResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::path_exam::RecordOdomResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::path_exam::RecordOdomResult_<ContainerAllocator>& v)
  {
    s << indent << "result[]" << std::endl;
    for (size_t i = 0; i < v.result.size(); ++i)
    {
      s << indent << "  result[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "    ", v.result[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PATH_EXAM_MESSAGE_RECORDODOMRESULT_H
